services:
  
  member-mysql:
    image: "mysql:latest"
    container_name: "member-mysql"
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234     
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  member-service:
    build:
      context: C:\Users\RANG\Desktop\msa-practice\member-project\member-service
      dockerfile: Dockerfile
    depends_on:
      - member-mysql
    image: "member-service"
    container_name: "member-service"
    ports:
      - 9001:9001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://member-mysql:3306/members?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    restart: always

 