spring:
  application:
    name: feign-client
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/java_practice?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
weather:
  url: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"
  service-key: "QL99OvgowvipV6jjgv1NoKwE8GMJnbROjRN0%2BxGQJz0497ViPFxnd04lXqgSskbJMcFoGhZGQeidvVCJYOY9Jg%3D%3D"
server:
  port: 2222
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.feignclient.model